name: CICD
on:
  push:
    branches:
    - '*'
jobs:
  build:
    name: build flutter
    runs-on: macos-11
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.8.1"
    steps:
      - uses: actions/checkout@v2
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAMT_FIREBASE_622115003 }}"
          projectId: camt-firebase-622115003
          channelId: live